### ISSUE TITLE
Invalid header when opening Twofish-encrypted database file

### ISSUE THREAD

**Issue by vaygr** [tobischo/gokeepasslib#109]
Steps to reproduce:

1. Create a Twofish-encrypted database with KeePassXC
2. Run the code:

```go
package main

import (
    "fmt"
    "github.com/tobischo/gokeepasslib/v3"
    "os"
)

func main() {
    file, _ := os.Open("/path/to/the/database.kdbx")

    db := gokeepasslib.NewDatabase()
    db.Credentials = gokeepasslib.NewPasswordCredentials("password")

    if err := gokeepasslib.NewDecoder(file).Decode(db); err != nil {
        fmt.Println("failed to decode db -", err)
    }
}
```

Error returned is `gzip: invalid header`. AES/ChaCha20 work fine.

**Comment by tobischo** [comment]
@vaygr Thank you for raising the issue. Do you happen to have an example file? I am not using KeepassXC anywhere.

Maybe I am missing something but the original Keepass2 does not seem to have twofish as an option when creating new files.

**Comment by tobischo** [comment]
![Keepass2](https://github.com/tobischo/gokeepasslib/assets/968947/f7271000-9094-450c-84e8-5c8f7cd71964)

Interesting. In Keepass2 it is only those 2 options

I'll take a look and see what I can do

**Comment by tobischo** [comment]
Apparently it is possible to add twofish as a plugin

https://keepass.info/plugins.html#twofishcipher

**Comment by tobischo** [comment]
@vaygr Please take a look at #110

**Comment by vaygr** [comment]
Thank you very much, that works as expected.

**Comment by tobischo** [comment]
Alright, will merge and release it probably this evening

**Comment by vaygr** [comment]
Thank you for quickly resolving this!
