### ISSUE TITLE
Integrity check failed

### ISSUE THREAD

**Issue by djherbis** [tobischo/gokeepasslib#15]
I'm using KeePass 2.29 with password + keyfile. I tried using ParseKeyFile and NewPasswordCredentials to build the credentials however it fails during decryption with "Database integrity check failed".

Any ideas?

Thanks, this looks like a really handy library.

**Comment by tobischo** [comment]
I can have a look on saturday (currently on vacation). Maybe @ironmig has an idea?
@djherbis: could you provide a sample of the code you are trying to run?

**Comment by tobischo** [comment]
Also a sample keepass file and password file would be great which causes this result.

My best guess so far is a bug in building the decrypt key from key and password.

**Comment by djherbis** [comment]
I'll do up a test case and share it sometime tomorrow. Thanks!

**Comment by ironmig** [comment]
Keepass 2.29 support in the library was dropped in https://github.com/tobischo/gokeepasslib/commit/312173478c63e91d6cc60c6aac94ff63100edcc3 . You can try checking out your head to 989ce56a90d684949a20171be1231ad9adb2e4fd or updating to keepass 2.30. I'll try to add something to optionally work with 2.29 soon (or you can do so in a pull request!).

**Comment by tobischo** [comment]
Thanks for pointing it out @ironmig!
I totally forgot about that! Then again I haven't been near my computer in 2 weeks...

**Comment by djherbis** [comment]
Oh no problem then, I'll upgrade to 2.30. 
Maybe your documentation should mention which version(s) you currently support?

**Comment by tobischo** [comment]
Yeah, it should.

**Comment by tobischo** [comment]
I added a note to the readme for now.
However this should only influence reading files created with gokeepasslib with Keepass2.
Reading existing Keepass files should work. If not this is not related to the incompatibility issue with Keepass v2.29 vs v2.30.

**Comment by djherbis** [comment]
Upgraded to v2.30 and decryption works! Thanks guys
