### ISSUE TITLE
Example for writing a DB file

### ISSUE THREAD

**Issue by joonas-fi** [tobischo/gokeepasslib#19]
Ohhh nice, thanks for writing this library! ❤️  It had me writing DB files in no time, even though the encoding support is somewhat undocumented :)

I'm building a hardware security module-ish thing on Raspberry Pi Zero W that works like Keepass but is web-based and only supports exposing one password at a time and it is granted by a press of a physical button (a hacker compromising my PC will not get access to all my passwords because she'd have to steal or hack my Pi as well). But because I cannot keep it with me when traveling etc, my project has to be able to export the database as Keepass-compatible file (with super strong pwd) for those rare occasions/emergencies when I need to access pwds on my phone when on the road/away from my normal equipment.

Would you accept it if I sent a PR with an example on how to write a DB file? I could put it in the examples folder and link to it from readme (perhaps reading is the most important part so write example is not needed there).

You could also update the repo summary to "A library to read/**write** keepass 2 files written in go"

**Comment by tobischo** [comment]
Yes, of course, any contribution is welcome.
I just didn't have the need for writing files at the moment and therefore didn't bother figuring this out some more/adding examples.
