### ISSUE TITLE
KDBX 4 Support

### ISSUE THREAD

**Issue by subdavis** [tobischo/gokeepasslib#20]
Now that KDBX version 4 has been launched, it would be _awesome_ if this code supported the changes outlined at http://keepass.info/help/kb/kdbx_4.html

I may take a look at this myself later.  I have a future project in mind and I'd like to use Go, but I think any new keepass-related projects going forward should strictly support v4.

**Comment by tobischo** [comment]
I absolutely agree.
I am aware that this file format was added to keepass, but I haven't had the time to implement it.

You are very welcome to contribute. I am not sure when I will find the time to add this to the code

**Comment by tobischo** [comment]
kdbx v4 support was added through ca16913f489fcf3b96cff4b206741a7515042cb2 and is now accessible in gokeepasslib/v2 (cd66b72ca9e704604a899b47b6b9a0eadcf845e7)
