### ISSUE TITLE
Bug in compression code, KeePassDroid on Android fails to parse DB

### ISSUE THREAD

**Issue by joonas-fi** [tobischo/gokeepasslib#23]
I wrote a database file and it failed to open in [KeePassDroid](https://play.google.com/store/apps/details?id=com.android.keepass&hl=en) (latest version, 2.2.0.9). The very same file opens in KeePass (2.38) on Windows.

The error it gave: `Unexpected end of ZLIB input stream`. I managed to get it to open in KeePassDroid by disabling compression:

```
db.Headers.CompressionFlags = gokeepasslib.NoCompressionFlag
```

I think the bug is here:
https://github.com/tobischo/gokeepasslib/blob/a6351206307a10fe80f1544fa2bbcbbf0d7d32d2/encoder.go#L65

Notice that the contents of the gzipped data buffer is read before `Close()` is called on the `Gzip.Writer` (the `Close()` is deferred so it will be called later). I guess there's some kind of footer (triggered by calling close; edit: [yes there is](https://golang.org/src/compress/gzip/gzip.go#L225)) that needs to be written and some Gzip readers are more strict in requiring it than some others (that's why it worked on KeePass but not in KeePassDroid).

I've done the same mistake in my code before with exact same symptoms (gzip decodes fine in software A, but not in software B), so that's why I knew to look for this issue given the error message and symptoms. :)

I think the fix is to do the `Close()` explicitly just before the `Bytes()` call.

Would you like for me to submit a PR?

**Comment by tobischo** [comment]
Nice that you noticed that! I haven't had issues with Keepass2Android, although I don't use it the file I write with gokeepasslib there at the moment 🤔

A PR would be very much appreciated 🙂
If not I think I can take a look tomorrow afternoon (CET)

**Comment by tobischo** [comment]
From your description I'd say calling `Close` after `Flush` and before `Bytes` should fix it?

**Comment by joonas-fi** [comment]
This is totally off-topic, but...

Some background where I'm using your library. I've made a "hardware security module" ([link](https://github.com/function61/pi-security-module), totally in progress) with Raspberry Pi that has a web interface that does basically the same that Keepass does (with the exception that to reveal a password, one has to press a physical button).

But I cannot have that device with me all the time, so I need to have an emergency solution (Keepass on my Android phone) to access the passwords.

So, in my project there's a feature to export the entire database in Keepass format. The export writes the file to a S3 bucket. Then there's this [Lambda function](https://github.com/function61/s3toifttt) (I just released it as open source) that acts as an adapter and posts the URL to the Keepass file to IFTTT. IFTTT takes care of the dirty details of writing the Keepass database to my Google Drive folder. And when the file is in Google Drive, I can access it from my phone.

**Comment by tobischo** [comment]
Sounds interesting :grinning: 
I am currently using owncloud to sync a keepass file between my different devices and operating systems.
I got a windows PC for playing and stuff at home while I use a mac at work. I can access my passwords there through [kp2](https://github.com/tobischo/kp2) although I really should improve on the interface and actually use the writing part of gokeepasslib. I currently mostly write the keepass file on my windows PC with the official client.

**Comment by joonas-fi** [comment]
kp2 sounds good also, that's probably something I'd use for a cross-platform Keepass if I wasn't developing this over-engineered project I mentioned... :D Lately I've been a bit of a security nerd, mainly because it poses interesting thought exercises and challenges. Otherwise [it's probably in vain](https://xkcd.com/538/) though. ;)
