### ISSUE TITLE
Time Format Error And Header Hash mismatch

### ISSUE THREAD

**Issue by ywwzwb** [tobischo/gokeepasslib#26]
I made a kdbx with the example-writing file and open it with MacPass. MacPass told me that the header hash is missmatch. After debuging the MacPass and gokeepasslib, I found gokeepass did not write the head hash in meta, and seems that the time format is not right, in the example.kdbx and other  kdbx files which generated by MacPass, the time string is somthing like "2015-06-19T15:38:38Z", but 
in the example-writing.kdbx, the time string is "2018-06-09T11:54:47.26862+08:00".

I made a pull request so you can see what I did for these issue.

**Comment by tobischo** [comment]
Thank you for pointing this out and creating a pull request.

It's interesting, that Keepass2 does not seem care about this, however the timestamps are in fact written in UTC, so following that certainly makes sense.
It stands to reason that opening an issue with MacPass might additionally make sense, since it is a valid time string.

I'll take a closer look at the pull request later

**Comment by ywwzwb** [comment]
I've read the source code of keepass offical c#  client version 2.39.1, [link here](https://sourceforge.net/projects/keepass/files/KeePass%202.x/2.39.1/) ,version 2.30, [link here](https://sourceforge.net/projects/keepass/files/KeePass%202.x/2.30/).
In the TimeUtil.cs, the client use `SerializeUtc` function to serialize datetime, the implementation are similar, 
``` c#
public static string SerializeUtc(DateTime dt)
{
	string str = dt.ToUniversalTime().ToString("s");
	if(str.EndsWith("Z") == false) str += "Z";
	return str;
}
```
It uses the `ToString("s")` to format the datetime.
The Microsoft document, l[ink here](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#Sortable), says that the format 's' yyyy'-'MM'-'dd'T'HH':'mm':'ss'
So, the final time format is something like '2018-06-01T12:00:00Z'

**Comment by tobischo** [comment]
I am sorry, I should have been more specific about what I meant regarding "caring about it":
Keepass2 is able to read time strings even if they are not in `2018-06-01T12:00:00Z` format

However it is fine for me to explicitly write them out in that format and in UTC.

Same goes for the header hash.
I'll open another issue to actually verify that the hash is correct on read.

**Comment by tobischo** [comment]
While adding tests I noticed that your version would only work if the time.Time values were already in UTC. I fixed it to ensure that it is actually marshaled as UTC
