### ISSUE TITLE
Hash mismatch

### ISSUE THREAD

**Issue by ywwzwb** [tobischo/gokeepasslib#29]
In the latest code, I found that you make some code to check the header hash.
I notice that the  way you write header fields in specific order, Comment>CipherID>CipherID .etc, but some kdbx file header fields may have diffrent order , like the kdbx file which is generated by MacPass.
It will cause the header data missmatch with the original header, so the hash will not match.
I think the best way is to save the original header data, and use it to check header hash.

**Comment by tobischo** [comment]
You are absolutely correct. I made a change now that should fix that.
Please give it a try and get back to me on whether it solves the issue for you or not

**Comment by ywwzwb** [comment]
it works, thanks for take time on it.

**Comment by tobischo** [comment]
Thanks for reporting it :+1:
