### ISSUE TITLE
Missing v2 path?

### ISSUE THREAD

**Issue by bcicen** [tobischo/gokeepasslib#31]
Running the example fails due to missing v2 path:

`
cannot find package "github.com/tobischo/gokeepasslib/v2" in any of:
...
`

**Comment by tobischo** [comment]
Thank you for opening this issue.
With the given information however I cannot reproduce it.

If you want me to look into it, I require some more information.

What go version did you use?
How did you download gokeepasslib?
Are you trying to execute it inside or outside of the GOPATH?
If you are using go 1.11: is GO111MODULE set? If yes: to which value?
What other steps did you take to reach this result? Can you reproduce it yourself from scratch?

**Comment by bcicen** [comment]
Go 1.11; `GO111MODULE`

I missed that this package was module-ized, so `github.com/tobischo/gokeepasslib/v2` is only valid import from within another project using modules.

In an non-module project, `import github.com/tobischo/gokeepasslib` works just fine -- readme example just had me confused for a moment

**Comment by tobischo** [comment]
I made a minor change to the readme which hopefully makes this more obvious
