### ISSUE TITLE
How to remove groups and entries?

### ISSUE THREAD

**Issue by Raggaer** [tobischo/gokeepasslib#32]
Hello. I am not sure how should I delete a group from a database...

I currently modify the group slice and encode the database, however this seems to corrupt my database and all passwords start to be wrong.

I do the same approach for entries.

What should I do to delete groups and entries?
Thanks

**Comment by tobischo** [comment]
Are you unlocking the protected entries and then re-locking them before writing the updated file?
Keepass2 uses a stream cipher on the protected values (e.g. passwords) to protect the passwords somewhat even while the file is opened and in memory.
This requires a certain order to the entries. If an entry is just removed, the stream cipher would not reach the same state on the following password and the password would start to be wrong.

I'd therefore recommend, that you call https://godoc.org/github.com/tobischo/gokeepasslib#Database.UnlockProtectedEntries before deleting passwords or adding new ones and https://godoc.org/github.com/tobischo/gokeepasslib#Database.LockProtectedEntries after you are done

I attached a list of examples with which you could recreate that behaviour without affecting your file.
[gkp-ex.zip](https://github.com/tobischo/gokeepasslib/files/2730288/gkp-ex.zip)

Please let me know if that solves your issue.

If not I'd ask you to provide a snippet of the code you are currently using.

**Comment by tobischo** [comment]
I also added a delete example to the examples list:

https://github.com/tobischo/gokeepasslib/blob/7ba4a3b788585a6ff1646b274096300c1ea9312e/examples/example-deleting.go

**Comment by Raggaer** [comment]
After looking at the example it worked fine, for some reason my order of unlock/lock was wrong.
Thanks for the help
