### ISSUE TITLE
Question about entry history

### ISSUE THREAD

**Issue by Raggaer** [tobischo/gokeepasslib#34]
Hello, when I modify an entry (lets say I modify Title, UserName, Password and URL) I should create a history struct, append 4 entries (foreach value modified) and append that history into entry.Histories?

Thanks

**Comment by tobischo** [comment]
Hi Raggaer,
entry.Histories are a list of what the entries used to be like.
Therefore it can actually show the change to multiple fields within one entry (as the original entry would be copied and added to the list)
As far as I know the original Keepass2 does not create a new entry for each individual field change but considers a change to an entry all fields changed at once.
Therefore it is up to you whether you want to add one entry or more.
Technically you do not even have to add these entries at all. Keepass2 and other programs supporting the file format just won't know about the previous states of an entry then.

**Comment by Raggaer** [comment]
Thanks for the answer
