### ISSUE TITLE
Error while unmarshaling KDBX4 new entries

### ISSUE THREAD

**Issue by Footmau** [tobischo/gokeepasslib#40]
Steps to reproduce:

- Open KDBX4 database
- Create new entry or group
- Save and try to open in KeePass desktop

Root cause is timestamps are always formatted.
I will prepare the merge request.

**Comment by Footmau** [comment]
@tobischo could you please grant me acces to create new branch fo the issue?

**Comment by tobischo** [comment]
Please create a fork and a pull request based on that

**Comment by Footmau** [comment]
https://github.com/tobischo/gokeepasslib/pull/41

**Comment by tobischo** [comment]
Thank you for the contribution.

Unfortunately this is a breaking change in the API of the library, which I would like to avoid.

Did you consider e.g. functional options?
- https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis

**Comment by Footmau** [comment]
Can we use optional bool argument? If not — functional options will be acceptable.
Thanks.

**Comment by tobischo** [comment]
Go only supports optional arguments in the form of slices, e.g.
```go
func(options ...bool) {
  // options would be a bool slice in the function - []bool{}
}
```
If you pass along an optional `bool` value like that, you'd be missing context.
What does which bool value mean?
With functional options that context is passed along.

**Comment by Footmau** [comment]
This is not problem for me to start support such options.
Please make implementation which is most convenient for old API consumers and for better library architecture.

**Comment by tobischo** [comment]
Take a look at #42 
```go
NewDatabase(WithDatabaseFormattedTime(false))
```
should provide the functionality you desire.

Adding a wrapper e.g.
```go
func WithKDBX4DatabaseFormat() DatabaseOption {
  return WithDatabaseFormattedTime(false)
}
```
could be a way to make it better understandable in the code. That would then also have to handle the other options necessary for creating a true kdbx4 file though 😄

**Comment by Footmau** [comment]
Yes, this is fine for me.
Would be great if we will able also (fot future improvements) to choose encryption options and so on while creation new database, like official application do.

**Comment by tobischo** [comment]
The purpose of the functional options is to also allow adding functions as needed for other things.
So yeah, I don't see an issue with supporting things like that.
With this library almost every field is exported on purpose though, as I did not want to make any assumptions about how other people would like to use it.
Instead of using `NewEntry` it is also an option to set the fields as needed when initializing an entry or to edit the values on existing entries.

**Comment by Footmau** [comment]
Tested the change today, works well.
Code looks not very smooth, but for perspectives such approach probably is best way. I have no a lot of Go experience and can not appreciate design.
Thanks!

**Comment by tobischo** [comment]
The propagated functional optionals do not look smooth indeed.

The alternative could be option structs (not that nice because even an empty option struct would be required) or separate initializer functions

**Comment by tobischo** [comment]
Release the change as v2.1.0
