### ISSUE TITLE
TimeWrapper incorrectly read values on KDBX4

### ISSUE THREAD

**Issue by Footmau** [tobischo/gokeepasslib#47]
_Steps to reproduce:_
- Open DB in **original** KeePass app and open some entry.
- Open **History** tab and remember creation time.
- Save DB.
- Open and save DB using gokeepasslib.
- Open DB in **original** KeePass app and open the entry.
- Open **History** tab.

_Expected behaviour:_
The creation time is the same as before.

_Observed behaviour:_
The creation time is 1 day and few seconds later than before.

**Comment by tobischo** [comment]
Thank you for reporting this.
Fixed in v2.1.2

**Comment by Footmau** [comment]
Thanks for fix.
Days are ok now, but minutes and secons are still changes:

`<CreationTime>2019-08-03T08:**47:49**Z</CreationTime>`

`<CreationTime>2019-08-03T08:**48:58**Z</CreationTime>`

**Comment by tobischo** [comment]
You are right, my solution did not cover every case and just one specific to my test data.
Addressed that in v2.1.3

**Comment by Footmau** [comment]
Should we reopen the issue?

**Comment by tobischo** [comment]
Only if v2.1.3 still doesn't solve it for you.
In that case I'd need more information and sample data, as I haven't been able to recreate the issue now.

**Comment by Footmau** [comment]
Oh, it's working. Sorry for misunderstending.
Thanks a lot for the fixes.
