### ISSUE TITLE
Open time optimization

### ISSUE THREAD

**Issue by Footmau** [tobischo/gokeepasslib#50]
Some users have problems with long time database opening. Probably it is possible do not decode encrypted fields while loading db file?

I offer decode only necessary field when user request it. So we can significantly improve database open time and a little bit disimprove work with every entry that contains encrypted data.

**Comment by tobischo** [comment]
Can you put 'long' into context by providing a time value?
Personally I never had the feeling that it takes too long, but I suppose that depends on the size of the file and the hardware it is executed on.
Could you provide more details on that?

As for the encrypted fields:
What exactly are you referring to?
The whole database needs to be decrypted in order to access information.
Some fields are then still encrypted. This encryption is done via a stream cipher which might make this possible for read access (skip ahead in the stream until you get to the number of bytes), however in order to keep this working for write access, you'd then need to decrypt at least everything following that entry and then re encrypt it, making the individual change process longer.

**Comment by Footmau** [comment]
Sorry for lack of accuracy, I can not provide any average time value. But some users doesn't get opened database at all (probably more than 10 seconds).
They are comparing performance to alternative KeePass applications.
On my devices I have no such problems, but I didn't test it with big files (my test databases is about 10 KB).

I will analyse source code later today, probably some ideas will appear.
Thanks.

**Comment by tobischo** [comment]
Are "they" just testing it for benchmarking purposes or is there an actual use case involved?
What's the usage scenario which sets the 10 second timeout?

With a more detailed set of information about the case where this causes a problem, it would be possible to analyze the issue and improve the performance where it causes issues.
I am afraid that without that information and a before/after benchmark there is just no way to deterministically make changes and improve things for them.

**Comment by Footmau** [comment]
This is actual use cases. I'm using the library in Android application. There are a lot of devices, and I receive a lot of feedback by users. Some of them have flagship devices (for example Huawei P30 Pro), but also have problems with open time. There is no any timeout, 10 seconds is just my suggestion, because some users says that database doesn't opens at all and process is hanging on. Other users says that open process takes "long time".

I'm afraid that I can not request database files because it is sensitive information for users. But I asked to clarify file size, which fields are encrypted and so on. I'll let you know as soon as I'll receive it.

**Comment by Footmau** [comment]
Some user replies me, hope you understand German:

> Durch Zufall liess ich das Programm geöffnet (durch eine Ablenkung), als ich es das erste Mal benutzte. Ich dachte schon an ein unbrauchbares Programm und wollte es deinstallieren, als es plötzlich öffnete.
> 
> Das Öffnen dauert 22! sec bevor man den Fingerprint auslösen kann. Aber da das Programm in allen Punkten für mich besser geeignet ist als alle andere Konkurrenzprogramme, behalte ich es.
> Es öffnet jedes Mal zuverlässig nach 22 sec.
> Ich muss dazu erwähnen, dass die kdbx Datei und auch das key file auf meiner NAS liegen!
> Bei anderen Apps verursacht dies jedoch keine merkliche Verzögerung!
> 
> Programmgösse:             72KB
> Enthält ausser den Passwörtern keine verschlüsselte Felder.

**Comment by Footmau** [comment]
Probably this is some architecture issue on Huawei devices.
Sorry for disturbing you.

**Comment by tobischo** [comment]
Yes, I understand german

Rough translation:
> I left the program open by accident (due to a distraction), when I first used the program.
> I already thought that the program was impractical and was about to uninstall it when I suddenly opened it.
>
> Opening the file took 22! seconds before the fingerprint could be triggered.
> Since the program is better suited in all relevant points for me, I'll keep it.
> It opens reliably after 22 seconds.
> I have to mention that the kdbx file and the key file are located on my NAS.
> For other apps this does not cause any noticeable delays though.
> 
> Program size: 72KB
> Does not contain encrypted fields except for the passwords.

It's fine, it would actually be interesting to see if a kdbx file with 72kb size could cause such issues.
However I am wondering if the loading of the kdbx and key file wouldn't be the cause of such issues

**Comment by Footmau** [comment]
Thanks, I already translated it with GTranslate :)
Just thought it is your native language, could be better for understanding.
