### ISSUE TITLE
I used gokepasslib in my project and I want to let you know

### ISSUE THREAD

**Issue by MarErm27** [tobischo/gokeepasslib#56]
I wrote a story at medium for project where Gokepasslib is in use. May I share it with you? https://medium.com/@ermmarat/workaround-for-limitation-of-10-smart-card-readers-in-windows-server-2012-r2-windows-8-and-later-3012eaa2de67

Source code:
https://github.com/MarErm27/workaroundForSmartCardsLimitationInWindows
https://github.com/MarErm27/readAndWriteKeepass
https://github.com/MarErm27/getCertificateData

I'm looking for work as a Golang developer, I was wondering, if I may ask you for help to find it.
My Email: ErmMarat@Gmail.com
My resume: https://trade.3park.online/resume
My last project is a bid simulator for group training to participate in the BID: https://trade.3park.online/
[Ermeshev_Marat.pdf](https://github.com/tobischo/gokeepasslib/files/4436458/Ermeshev_Marat.pdf)

**Comment by tobischo** [comment]
Hi Marat,

thank you for sharing. It is really great to see that the keepass implementation is of help to you 👍 
It would be interesting to learn more about the other solutions you considered and how you ended up using keepass. In the article you wrote that it was from a recommendation by a coworker.
Did you consider alternative solutions for secret storing, such as https://www.vaultproject.io/ ?

Regarding work:
The company I work for is hiring, however eventually that would require relocation to Berlin, Germany.

We use Ruby and go in production, so if that is of interest to you, feel free to send a mail to
Did you check the gopher slack?
https://invite.slack.golangbridge.org/

**Comment by MarErm27** [comment]
Hello!
I'm trying to add an invoice to QuickBooks by web connector, but it can't find an item and because of that can't create an invoice. How to create an item if it's not found in a separate transaction
I guess I need to use this https://developer.intuit.com/app/developer/qbdesktop/docs/api-reference/qbdesktop/iteminventoryadd
but I can't find an example of how to do it in Java

here is an example of how to add a Customer

public String addCustomer() throws QBDB.DbException, JAXBException, URISyntaxException, IOException, ClassNotFoundException {
Input input = getInput();
List invoices = input.getInvoices();
String xml = "";
QBXML qbXML = new QBXML();
QBXMLMsgsRq xmlMsgRq = new QBXMLMsgsRq();
xmlMsgRq.setOnError("continueOnError");
qbXML.setQBXMLMsgsRq(xmlMsgRq); List reqList = xmlMsgRq.getHostQueryRqOrCompanyQueryRqOrCompanyActivityQueryRq();
int i = 1; for (Invoice invoice : invoices) { CustomerRef ref = getCustomerRefForEmail(invoice.getEmail());
String idChk = ref.getListID();
if (idChk.equals("-1")) {
CustomerAddRqType customerAddRq = new CustomerAddRqType();
reqList.add(customerAddRq);
customerAddRq.setRequestID(i++ + "");
CustomerAdd cust = new CustomerAdd();
customerAddRq.setCustomerAdd(cust);
// cust.setEmail(invoice.getEmail());//email);
cust.setName("watchmaxx");
cust.setFirstName(invoice.getEmail());
cust.setCompanyName("watchmaxx");
}
}
xml = getRequestXml(qbXML);
return xml;
}

Please, help, how to add an item so QuickBooks can make an item reference

**Comment by tobischo** [comment]
So unfortunately I do not think that I can really help you there.
I have never worked with quickbooks and this is not a repo that is in any way related to quickbooks.

Without looking at the documentation in perfect detail, I would imagine the following:
```c#
ItemInventoryAddRqType itemAddRq = new ItemInventoryAddRq();
reqList.add(itemAddRq)
ItemInventoryAdd item = new ItemInventoryAdd();
itemAddRq.setItemAdd(item)
// set all relevant values on item
```

I can really only point you to their documentation or stackoverflow though.

**Comment by MarErm27** [comment]
I made a function below, it is based on your suggestion, but I'm not sure how to set a listId field, it's not available. 

public String addItem(String itemRefName) throws QBDB.DbException, JAXBException, URISyntaxException, IOException, ClassNotFoundException {
String[] itemData = itemRefName.split(":", 2);
System.out.println("=> item name" + itemData[0]);
System.out.println("=> item ref" + itemData[1]);
String xml = "";
QBXML qbXML = new QBXML();
QBXMLMsgsRq xmlMsgRq = new QBXMLMsgsRq();
xmlMsgRq.setOnError("continueOnError");
qbXML.setQBXMLMsgsRq(xmlMsgRq);

List<Object> reqList = xmlMsgRq.getHostQueryRqOrCompanyQueryRqOrCompanyActivityQueryRq();
int i = 1;
    ItemInventoryAddRqType itemAddRq = new ItemInventoryAddRqType();
    reqList.add(itemAddRq);
    ItemInventoryAdd item = new ItemInventoryAdd();
    itemAddRq.setItemInventoryAdd(item);
    item.setName(itemRefName+"Marat");
   // item.setListId
xml = getRequestXml(qbXML);
return xml;

}

here is a list of available fields may one of them be an alias for listId?
@xmlelement(name = "ListID")
protected String listID;
@xmlelement(name = "TimeCreated")
@XmlSchemaType(name = "anySimpleType")
protected String timeCreated;
@xmlelement(name = "TimeModified")
@XmlSchemaType(name = "anySimpleType")
protected String timeModified;
@xmlelement(name = "EditSequence")
protected String editSequence;
@xmlelement(name = "Name")
protected String name;
@xmlelement(name = "BarCodeValue")
protected String barCodeValue;
@xmlelement(name = "IsActive")
@XmlSchemaType(name = "anySimpleType")
protected String isActive;
@xmlelement(name = "ClassRef")
protected ClassRef classRef;
@xmlelement(name = "ItemDesc")
protected String itemDesc;
@xmlelement(name = "TaxRate")
protected String taxRate;
@xmlelement(name = "TaxVendorRef")
protected TaxVendorRef taxVendorRef;
@xmlelement(name = "SalesTaxReturnLineRef")
protected SalesTaxReturnLineRef salesTaxReturnLineRef;
@xmlelement(name = "ExternalGUID")
protected String externalGUID;
@xmlelement(name = "DataExtRet")
protected List dataExtRet;
@XmlAttribute(name = "Hjid")
protected Long hjid;

**Comment by MarErm27** [comment]
I've found listId in class ref and rewrited the method

  public String addItem(String itemRefName) throws QBDB.DbException, JAXBException, URISyntaxException, IOException, ClassNotFoundException {
    String[] itemData = itemRefName.split(":", 2);
    System.out.println("=> item name" + itemData[0]);
    System.out.println("=> item ref" + itemData[1]);
    String xml = "";
    QBXML qbXML = new QBXML();
    QBXMLMsgsRq xmlMsgRq = new QBXMLMsgsRq();
    xmlMsgRq.setOnError("continueOnError");
    qbXML.setQBXMLMsgsRq(xmlMsgRq);

    List<Object> reqList = xmlMsgRq.getHostQueryRqOrCompanyQueryRqOrCompanyActivityQueryRq();

    ItemInventoryAddRqType itemAddRq = new ItemInventoryAddRqType();
    reqList.add(itemAddRq);
    ItemInventoryAdd item = new ItemInventoryAdd();
    itemAddRq.setItemInventoryAdd(item);
    ClassRef classRef = new ClassRef();
    classRef.setFullName(itemData[0]);
    classRef.setListID(itemData[0]);
    item.setClassRef(classRef);
    xml = getRequestXml(qbXML);
    return xml;
  }

Now I'm trying to find out how to send this to web connector

**Comment by tobischo** [comment]
Best of luck

I cannot really help you with this

**Comment by MarErm27** [comment]
> 
> 
> Best of luck
> 
> I cannot really help you with this as I have no experience with quickbooks

You already helped me a lot, thank you very much

**Comment by MarErm27** [comment]
Hello, @tobischo 
I'm trying to create an admin portal in Go that will list users from the Firebase database and provide the ability to send emails to each of these users from this list.  What is a good way to do it? I've tried to start with GoAdmin, it looks good but I'm not sure how to change the template to make it show only what needs to be shown. Have you tried it?

**Comment by tobischo** [comment]
I have not used it, but I would assume that you could fork it and change the used templates if necessary.
Multiple templates appear to be available which makes me assume that there is the possibility to provide your own.
You will have to step through the code though or ask in gopher slack for more help

**Comment by MarErm27** [comment]
I've forked the template
https://github.com/MarErm27/themes/blob/master/adminlte/separation/public/pages/sidebar.tmpl

This is a sidebar. I'm trying to delete the posts section from the sidebar. I've already deleted it from the SQLite database, but it still appears in the template. I've made a search from all the project but world "posts" not found

**Comment by tobischo** [comment]
That might just be defined in the datamodel.
https://github.com/GoAdminGroup/go-admin/blob/344c5abc7a78e467c4986e13b1704be4239176c7/examples/datamodel/tables.go

However I would suggest that you just open an issue in https://github.com/GoAdminGroup/go-admin, asking the maintainers of the project for help on how to use it.
