### ISSUE TITLE
IconID / Where to / How To Store Icons?

### ISSUE THREAD

**Issue by npotts** [tobischo/gokeepasslib#66]
Hello!

I am looking to create a took that converts from a password manager to KeePass 2/3x,, and Most of the utility is 100% there.  However, I would like to retain the icons for entries if possible, but Im not really sure how to get the icons bundled into the structure.

It looks [Groups](https://github.com/tobischo/gokeepasslib/blob/v1.0.0/content.go#L147) and [Entries](https://github.com/tobischo/gokeepasslib/blob/v1.0.0/content.go#L196) both support an IconID, but I am not sure where to specify /  store the icon images.

I am also sure that there are some predefined ones (as a total wild guess 0x01- 0x50 are all 'well known', 0x51-0x120 are "reserved" or similar.  

Any pointers to Keypass's XML format for documentation, or hints where to look for these (most likely trivial connective tissue) would be most appreciated!

**Comment by npotts** [comment]
I think in order to do this I would need to create a PR here.

Poking around in the KeePassXC sources, it looks like in the [Metadata](https://github.com/keepassxreboot/keepassxc/blob/2423bede60914740854ceb37034464ff4ff09f89/tests/data/NewDatabase.xml#L23) block needs a `<CustomIcons>` section, and each Entry would need a `<CustomIconUUID>` reference back to the Custom Icon.

I am not familiar enough with the format w.r.t backwards compatability, but is this something that I could relatively easily add?

**Comment by npotts** [comment]
PR: https://github.com/tobischo/gokeepasslib/pull/67

**Comment by tobischo** [comment]
Released as v3.2.0 after merging #v67
