### ISSUE TITLE
Support CustomData in Entry

### ISSUE THREAD

**Issue by tomaluca95** [tobischo/gokeepasslib#76]
Would be nice to be able to read/write CustomData in Entry

I think the change would be somewhere in `entry.go`
```go
...
	Binaries        []BinaryReference `xml:"Binary,omitempty"`
	CustomData      EntryCustomData   `xml:"CustomData"`
}

type EntryCustomData struct {
	Items []CustomData `xml:"Item"`
}
```

this will allow working with `KeePassXC-Browser Settings`

**Comment by tobischo** [comment]
Could you provide an example file against which I could verify that it behaves as intended?

**Comment by tomaluca95** [comment]
[Test Database 76.zip](https://github.com/tobischo/gokeepasslib/files/8486459/Test.Database.76.zip)

Password: Test

**Comment by tobischo** [comment]
I'd rather go with adding custom data like this:
```go
	Binaries        []BinaryReference `xml:"Binary,omitempty"`
	CustomData      []CustomData      `xml:"CustomData>Item"`
}
```
This is the same way it is defined for metadata, which would change your piece of code to
```go
// ...
fmt.Println(entry.CustomData[0].Value)
```

**Comment by tobischo** [comment]
Added as v3.2.5

**Comment by tomaluca95** [comment]
Tested in my use case (generate/update entries from external data sources) and works fine. Thanks
