### ISSUE TITLE
Incorrect KDBX4 binaries referencing after remove

### ISSUE THREAD

**Issue by Footmau** [tobischo/gokeepasslib#80]
The reason for that appears to be that in KDBX4 the ID is actually not encoded. So when you decode it, it starts to count again at ID 0. If you are still referencing a different ID, it causes the issue.

_Originally posted by @tobischo in https://github.com/tobischo/gokeepasslib/pull/79#discussion_r881850893_

**Comment by Footmau** [comment]
@tobischo Tried to implement my vision of garbage collector here https://github.com/tobischo/gokeepasslib/pull/81
Didn't tested yest, but if you like the solution I could add tests.

**Comment by tobischo** [comment]
Released as v3.4.0
