### ISSUE TITLE
encodeRawContent() padding case missed in encoder.go

### ISSUE THREAD

**Issue by cndonnie** [tobischo/gokeepasslib#87]
In func encodeRawContent(...) , padding calculation miss one case:  len(content)%16 == 0 , in this case no padding made, but any decoder which care about padding bytes will read last byte as padding and found the padding repeat wrong times. Just add a 16-bytes padding which value is 16 will fix it.

such as:
```diff
diff --git a/encoder.go b/encoder.go
index 823df3e..75c5fc9 100644
--- a/encoder.go
+++ b/encoder.go
@@ -138,7 +138,7 @@ func encodeRawContent(db *Database, content []byte, transformedKey []byte) (enco
        }

        // Adds padding to data as required to encrypt properly
-       if len(content)%16 != 0 {
+       if len(content)%16 != 0 || true { // Always add padding, even mod result is 0
                padding := make([]byte, 16-(len(content)%16))
                for i := 0; i < len(padding); i++ {
                        padding[i] = byte(len(padding))
```

**Comment by tobischo** [comment]
Then we might just as well skip the condition check after all? It would be kind of pointless to add `|| true` anywhere, since that will always be true.

**Comment by tobischo** [comment]
I applied a change to always add padding
